platform :ios, '9.2'

use_frameworks!
inhibit_all_warnings!

target 'ImagePickerDemo' do
	pod 'ImagePicker', :git => 'https://github.com/sotheavuthnguon/ImagePicker.git',  :branch => 'sotheavuth'
end
